aliyun:
  oss:
    accessKeyId: XXXXXXXXXXXXXXXXXXXXXXXXXXX  #your oss keyId
    accessKeySecret: XXXXXXXXXXXXXXXXXXXXXXXXXXX  #your oss keySecret
    bucketName: XXXXXXXXXXXXXXXXXXXXXXXXXXX        #your bucketName
    endpoint: XXXXXXXXXXXXXXXXXXXXXXXXXXX

    # 由于隐私问题就不提供了
